title: Cladious First Blog
author: MysterMan15
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Testing how this will appear when GitHyb launches the page
 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
